module;

module Core.Constants;

namespace Core::Constants {
// 中文字符串定义
const LocalizedStrings ZH_CN = {
    L"旋转吧大喵",
    L"选择窗口",
    L"窗口比例",
    L"分辨率",
    L"重置窗口",
    L"修改热键",
    L"打开配置文件",
    L"退出",
    L"已选择窗口",
    L"窗口调整成功！",
    L"窗口调整失败。可能需要管理员权限，或窗口不支持调整大小。",
    L"未找到目标窗口，请确保窗口已启动。",
    L"窗口已重置为屏幕大小。",
    L"重置窗口尺寸失败。",
    L"请按下新的热键组合...\n支持 Ctrl、Shift、Alt 组合其他按键",
    L"热键已设置为：",
    L"热键设置失败，已恢复默认热键。",
    L"配置文件说明：\n1. [AspectRatioItems] 节用于添加自定义比例\n2. [ResolutionItems] "
    L"节用于添加自定义分辨率\n3. 保存后重启软件生效",
    L"窗口比例调整工具已在后台运行。\n按 [",
    L"] 可以显示/隐藏调整窗口",
    L"语言",
    L"中文",
    L"English",
    L"热键注册失败。程序仍可使用，但快捷键将不可用。",
    L"格式错误：",
    L"请使用正确格式，如：16:10,17:10",
    L"请使用正确格式，如：3840x2160,7680x4320",
    L"加载配置失败，请检查配置文件。",
    L"隐藏任务栏",
    L"调整时置底任务栏",
    L"浮窗模式",
    L"显示浮窗",
    L"关闭浮窗",
    L"截图",
    L"截图成功，已保存至: ",
    L"预览窗",
    L"打开相册",
    L"使用指南",
    L"此功能需要 Windows 10 1803 或更高版本，已自动禁用。",
    L"叠加层",
    L"预览窗和叠加层功能冲突，已自动关闭另一功能",
    L"黑边模式",
    L"切换窗口边框",
};

// 英文字符串定义
const Constants::LocalizedStrings Constants::EN_US = {
    L"SpinningMomo",
    L"Select Window",
    L"Window Ratio",
    L"Resolution",
    L"Reset",
    L"Modify Hotkey",
    L"Open Config",
    L"Exit",
    L"Window Selected",
    L"Window adjusted successfully!",
    L"Failed to adjust window. May need administrator privileges, or window doesn't support "
    L"resizing.",
    L"Target window not found. Please ensure the window is running.",
    L"Window has been reset to screen size.",
    L"Failed to reset window size.",
    L"Please press new hotkey combination...\nSupports Ctrl, Shift, Alt with other keys",
    L"Hotkey set to: ",
    L"Hotkey setting failed, restored to default.",
    L"Config File Help:\n1. [AspectRatioItems] section for custom ratios\n2. [ResolutionItems] "
    L"section for custom resolutions\n3. Restart app after saving",
    L"Window ratio adjustment tool is running in background.\nPress [",
    L"] to show/hide the adjustment window",
    L"Language",
    L"中文",
    L"English",
    L"Failed to register hotkey. The program can still be used, but the shortcut will not be "
    L"available.",
    L"Format error: ",
    L"Please use correct format, e.g.: 16:10,17:10",
    L"Please use correct format, e.g.: 3840x2160,7680x4320",
    L"Failed to load config, please check the config file.",
    L"Hide Taskbar",
    L"Lower Taskbar When Resizing",
    L"Floating Mode",
    L"Show",
    L"Hide",
    L"Capture",
    L"Screenshot saved to: ",
    L"Preview",
    L"Screenshots",
    L"User Guide",
    L"This feature requires Windows 10 1803 or higher and has been disabled.",
    L"Overlay",
    L"Preview Window and Overlay Window cannot be used simultaneously, and one of the functions "
    L"has been automatically disabled.",
    L"Letterbox",
    L"Toggle Window Border",
};

}  // namespace Core::Constants