#include "constants.hpp"

// 中文字符串
const LocalizedStrings ZH_CN = {
    TEXT("旋转吧大喵"),
    TEXT("选择窗口"),
    TEXT("窗口比例"),
    TEXT("分辨率"),
    TEXT("重置窗口"),
    TEXT("修改热键"),
    TEXT("显示操作提示"),
    TEXT("游戏置顶"),
    TEXT("打开配置文件"),
    TEXT("退出"),
    TEXT("已选择窗口"),
    TEXT("窗口调整成功！"),
    TEXT("窗口调整失败。可能需要管理员权限，或窗口不支持调整大小。"),
    TEXT("未找到目标窗口，请确保窗口已启动。"),
    TEXT("窗口已重置为屏幕大小。"),
    TEXT("重置窗口尺寸失败。"),
    TEXT("请按下新的热键组合...\n支持 Ctrl、Shift、Alt 组合其他按键"),
    TEXT("热键已设置为："),
    TEXT("热键设置失败，已恢复默认热键。"),
    TEXT("配置文件说明：\n1. [CustomRatio] 节用于添加自定义比例\n2. [CustomResolution] 节用于添加自定义分辨率\n3. 保存后重启软件生效"),
    TEXT("窗口比例调整工具已在后台运行。\n按 ["),
    TEXT("] 可以显示/隐藏调整窗口"),
    TEXT("语言"),
    TEXT("中文"),
    TEXT("English"),
    TEXT("热键注册失败。程序仍可使用，但快捷键将不可用。"),
    TEXT("格式错误："),
    TEXT("请使用正确格式，如：16:10,17:10"),
    TEXT("请使用正确格式，如：3840x2160,7680x4320"),
    TEXT("加载配置失败，请检查配置文件。"),
    TEXT("隐藏任务栏"),
    TEXT("调整时置底任务栏"),
    TEXT("浮窗模式"),
    TEXT("显示浮窗"),
    TEXT("关闭浮窗")
};

// 英文字符串
const LocalizedStrings EN_US = {
    TEXT("SpinningMomo"),
    TEXT("Select Window"),
    TEXT("Window Ratio"),
    TEXT("Resolution"),
    TEXT("Reset Window"),
    TEXT("Modify Hotkey"),
    TEXT("Show Tips"),
    TEXT("Game Topmost"),
    TEXT("Open Config"),
    TEXT("Exit"),
    TEXT("Window Selected"),
    TEXT("Window adjusted successfully!"),
    TEXT("Failed to adjust window. May need administrator privileges, or window doesn't support resizing."),
    TEXT("Target window not found. Please ensure the window is running."),
    TEXT("Window has been reset to screen size."),
    TEXT("Failed to reset window size."),
    TEXT("Please press new hotkey combination...\nSupports Ctrl, Shift, Alt with other keys"),
    TEXT("Hotkey set to: "),
    TEXT("Hotkey setting failed, restored to default."),
    TEXT("Config File Help:\n1. [CustomRatio] section for custom ratios\n2. [CustomResolution] section for custom resolutions\n3. Restart app after saving"),
    TEXT("Window ratio adjustment tool is running in background.\nPress ["),
    TEXT("] to show/hide the adjustment window"),
    TEXT("Language"),
    TEXT("中文"),
    TEXT("English"),
    TEXT("Failed to register hotkey. The program can still be used, but the shortcut will not be available."),
    TEXT("Format error: "),
    TEXT("Please use correct format, e.g.: 16:10,17:10"),
    TEXT("Please use correct format, e.g.: 3840x2160,7680x4320"),
    TEXT("Failed to load config, please check the config file."),
    TEXT("Hide Taskbar"),
    TEXT("Lower Taskbar When Resizing"),
    TEXT("Floating Mode"),
    TEXT("Show Window"),
    TEXT("Close Window")
}; 